{% set version = "1.4.12" %}

package:
  name: kealib
  version: {{ version }}

source:
  url: https://github.com/ubarsc/kealib/releases/download/kealib-{{ version }}/kealib-{{ version }}.tar.gz
  sha256: 0b100e36b3e25e57487aa197d7be47f22e1b30afb16a57fdaa5f877696ec321e

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('kealib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
  run:
    - hdf5

test:
  requires:
    - libgdal
  commands:
    # check we haven't broken GDAL
    - gdal_translate --formats

about:
  home: http://kealib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
