{% set version = "1.4.12" %}

package:
  name: kealib
  version: {{ version }}

source:
  url: https://bitbucket.org/chchrsc/kealib/downloads/kealib-{{ version }}.tar.gz
  sha256: 0b100e36b3e25e57487aa197d7be47f22e1b30afb16a57fdaa5f877696ec321e

build:
  number: 0
  run_exports:
    # no idea.  Sticking with minor version.  C++ lib, so may need tighter.
    - {{ pin_subpackage('kealib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
    - msinttypes  # [win and vc<14]

test:
  commands:
    - conda inspect linkages -p $PREFIX kealib  # [not win]
    - conda inspect objects -p $PREFIX kealib  # [osx]

about:
  home: http://kealib.org/
  license: MIT
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - msarahan
