{% set version = "1.4.7" %}

package:
  name: kealib
  version: {{ version }}

source:
    url: https://bitbucket.org/chchrsc/kealib/downloads/kealib-{{ version }}.tar.gz
    sha256: ec38751b3b555d3a26f0c7445f2d2cd9d7c3a3502237519a206a50cb58df56ec
    patches:
        # create links libkea.so, libkea.so.1.4 etc. Fixed in next version
        - soversion.patch

build:
    number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - hdf5

test:
  commands:
    - conda inspect linkages -p $PREFIX kealib  # [not win]
    - conda inspect objects -p $PREFIX kealib  # [osx]

about:
  home: http://kealib.org/
  license: MIT
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - msarahan
