{% set name = "kealib" %}
{% set version = "1.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ubarsc/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 815b8d335b8d4b9048baf863cdd3959d12210f158a86f6a0d1954c7d39ce6db0

build:
  number: 1
  run_exports:
    # no idea.  Sticking with minor version.  C++ lib, so may need tighter.
    - {{ pin_subpackage('kealib', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5 {{ hdf5 }}
  run:
    - hdf5

about:
  home: https://kealib.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format
  description: |
    KEA is an image file format, named after the New Zealand bird, that provides a full implementation
    of the GDAL data model and is implemented within a HDF5 file. A software library, libkea, is used
    to access the file format. The format has comparable performance with existing formats while
    producing smaller file sizes and is already within active use for a number of projects
    within Landcare Research, New Zealand, and the wider community"
  doc_url: https://gdal.org/drivers/raster/kea.html
  dev_url: https://github.com/ubarsc/kealib

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - msarahan
