{% set version = "1.4.8" %}

package:
    name: kealib
    version: {{ version }}

source:
    url: https://bitbucket.org/chchrsc/kealib/downloads/kealib-{{ version }}.tar.gz
    sha256: 0f24d8478865abcb17865c8f49c0370095726c529b8ac373ffae018ad3d40a02

build:
    number: 0
    run_exports:
      # should be compatibility between minor releases
      - {{ pin_subpackages('kealib', min_pin='x.x', max_pin='x.x') }}

requirements:
    build:
        - cmake
        - hdf5 1.10.1
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    run:
        - hdf5 1.10.1

test:
    requires:
        - libgdal 2.2.*
    commands:
        # check we haven't broken GDAL
        - gdal_translate --formats
        - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
        - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
    home: http://kealib.org/
    license: MIT
    summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.

extra:
    recipe-maintainers:
        - gillins
        - danclewley
