{% set version = "1.4.9" %}

package:
  name: kealib
  version: {{ version }}

source:
  url: https://bitbucket.org/chchrsc/kealib/downloads/kealib-{{ version }}.tar.gz
  sha256: 1c80489f17114a229097c2e8c61d5e4c82ea63ae631c81a817fef95cfd527174
  patches:
    # by default kealib forces C++98 mode which breaks other things built in C++11 mode
    - disablecpp98.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('kealib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
  run:
    - hdf5

test:
  #requires:
  #  - libgdal 2.2.*
  commands:
    # check we haven't broken GDAL
    #- gdal_translate --formats
    # GDAL check disabled since we don't have a version of GDAL linked against the new HDF5

about:
  home: http://kealib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
