travis:
  secure:
    BINSTAR_TOKEN: TvHSxYUWK3rmy4vywglEYHB9k/tQs6O07ocyz1/tI1JsEYnLALQqSXzFth6uOY2nCzbAdfr9v8rkCPzb69IsgqzzdR+v44y/TZhhX8BPziyPaUSdL3OU6xXr01ROMVznRIdu+O4S+xbYCethcOFaJwqEHnEiAzWdjB7+/UfIFKunm10DLlkcY8MOpsA3t+0jaKS1Yc3KUY7u47cPtqqZw7Ua6Op69TmuJOcSUUUObHedvATeVRkuSJZBCsKddG603+bFInj0FUpvedl7QWduOgxlEVJ3SEDmMKXETsvPvc0vkLDybqhnWvtPPZqgw/Mf31A0oVjgjAF+ISiiwXXWdMrim6ki3CZ9fZ08//8jvOhsTZxiAkEVDRzKdfPuVnSvwoIKsT0WVRSdl8tz8plMoWgKcoMIKaBvGD/+bP2TqND1m3VOvho2KO0iR1ADPWFXOHY2tLbxuwO0xoacH32O9VFDtIc4IqTqzZQfW4UgfycwZTay+1ZAZb1H6h+J/x7+UMmYBWPU34iMOa9ll0kzZ3XsMu9PYSL8hGSXdAEql0Avgg8ad/5jo9ZP3Cpse1w19zfGQxu5I6W49NVpFgSMFkzQWvDZ1adyGvzgThUlYd3zjJchghinJscaRLRXdM2DWBN3yxMId6Z+E11nd4KrvKExQ0Sp3p1yjE+V5ig3l6o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
